// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI9J8RzgwGIIhvvqMx-mMmxbZIq33S1QM',
    appId: '1:149713584952:android:db00507cd6addf7f3d37cd',
    messagingSenderId: '149713584952',
    projectId: 'event-app-c48c8',
    databaseURL: 'https://event-app-c48c8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'event-app-c48c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApwney5tZWnggCnltPz5yAxKF7KbpG_vY',
    appId: '1:149713584952:ios:64411fd45f7442213d37cd',
    messagingSenderId: '149713584952',
    projectId: 'event-app-c48c8',
    databaseURL: 'https://event-app-c48c8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'event-app-c48c8.appspot.com',
    iosClientId: '149713584952-dhgiq6mbhupcd0v6mqcgn18p94jek398.apps.googleusercontent.com',
    iosBundleId: 'com.asper.eventApp',
  );
}
